version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app  # Mapeia o diretório local 'app' para o diretório '/app' dentro do contêiner
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
