# Generated by Django 4.2 on 2024-04-05 19:51

from django.db import migrations, models
import funcionarios.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=30)),
                ('sobrenome', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=14, validators=[funcionarios.models.validator_cpf])),
                ('data_nascimento', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('salario_base', models.CharField(blank=True, max_length=10)),
                ('salario_liquido', models.CharField(blank=True, max_length=10)),
                ('data_contratacao', models.DateTimeField(auto_now_add=True)),
                ('data_desligamento', models.DateTimeField(blank=True, null=True)),
                ('cnh', models.CharField(blank=True, max_length=11)),
                ('cnh_categoria', models.CharField(blank=True, choices=[('A', 'Categoria A'), ('B', 'CategoriB B'), ('C', 'Categoria C'), ('D', 'Categoria D')], max_length=20)),
                ('cnh_emissao', models.DateField(blank=True)),
                ('cnh_validade', models.DateField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
