# Generated by Django 4.2 on 2024-04-05 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adiantamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data', models.DateField(blank=True)),
                ('descricao', models.CharField(blank=True, max_length=50)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adiantamentos', to='funcionarios.motorista')),
            ],
            options={
                'verbose_name': 'Adiantamento',
            },
        ),
    ]
